# Generated by Django 2.0.6 on 2020-03-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typepersonne', models.PositiveSmallIntegerField(choices=[(1, 'Personne physique'), (2, 'Personne morale')], default=1)),
                ('nom', models.CharField(max_length=50, verbose_name='Noms ou Raison Sociale')),
                ('sexe', models.CharField(choices=[('F', 'Feminin'), ('M', 'Masculin')], max_length=1, verbose_name='Sexe')),
                ('nomContact', models.CharField(max_length=50, verbose_name='Noms Contact')),
                ('fonctionContact', models.CharField(max_length=25, verbose_name='Fonction Contact')),
                ('adresse', models.CharField(max_length=100, verbose_name='Adresse')),
            ],
            options={
                'ordering': ('nom',),
                'verbose_name': 'Abonnement',
            },
        ),
    ]
