# Generated by Django 2.0.6 on 2020-03-07 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='dateEdit',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='dateEnr',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Date d'enregistrement"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='sexe',
            field=models.CharField(choices=[('F', 'Feminin'), ('M', 'Masculin')], max_length=1, verbose_name='Sexe/Sigle'),
        ),
    ]
