# Generated by Django 2.0.6 on 2020-03-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0002_auto_20200307_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='fonctionContact',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Fonction Contact'),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='nomContact',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Noms Contact'),
        ),
    ]
