# Generated by Django 2.0.6 on 2020-03-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0003_auto_20200307_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='contact',
            field=models.CharField(default='', max_length=15, verbose_name='Téléphone'),
            preserve_default=False,
        ),
    ]
