# Generated by Django 2.0.6 on 2020-03-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0004_abonnement_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='sigle',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Sigle'),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='sexe',
            field=models.CharField(blank=True, choices=[('F', 'Feminin'), ('M', 'Masculin')], max_length=1, null=True, verbose_name='Sexe'),
        ),
    ]
