# Generated by Django 2.0.6 on 2020-03-09 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0005_auto_20200307_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codePays', models.IntegerField(verbose_name='Code du Pays')),
                ('nomPays', models.CharField(max_length=50, verbose_name='Nom du Pays')),
            ],
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbrVisa', models.IntegerField(verbose_name='Nombre de Visa')),
                ('dateIn', models.DateField(verbose_name="Date d'entrée prévue")),
                ('dateOut', models.DateField(verbose_name='Date de sortie prévue')),
                ('nbreIn', models.PositiveSmallIntegerField(choices=[(1, 'Passeport ordinaire'), (2, 'Passeport diplomatique'), (3, 'Passeport de service'), (4, 'Passeport officiel'), (5, 'Passeport spécial'), (6, 'Autre document')], default=2, verbose_name='Type Document de voyage')),
                ('nomContact', models.CharField(max_length=50, verbose_name='Nom du (de la) demandeur(euse')),
                ('dateNais', models.DateField(verbose_name='Date de naissance du (de la) demandeur(euse)')),
                ('nation', models.CharField(max_length=50, verbose_name='Nationalité du (de la) demandeur(euse)')),
                ('adresse', models.CharField(max_length=100, verbose_name='Adresse du (de la) demandeur(euse)')),
                ('email', models.CharField(max_length=50, verbose_name='Email du (de la) demandeur(euse)')),
                ('contact', models.CharField(max_length=15, verbose_name='Téléphone')),
                ('profession', models.CharField(max_length=25, verbose_name='Profession actuelle')),
                ('objet', models.PositiveSmallIntegerField(choices=[(1, 'Tourisme'), (2, 'Affaires'), (3, 'Visite à la famille ou à des amis'), (4, 'Culture'), (5, 'Sports'), (6, 'Visite officielle'), (7, 'Raisons médicales'), (8, 'Etudes'), (9, 'Transit aéroportuaire'), (10, 'Autre')], default=2, verbose_name='Objet du voyage')),
                ('info', models.CharField(max_length=200, verbose_name='Informations complémentaires')),
                ('hote', models.CharField(max_length=100, verbose_name="Nom de l'hôte (Personne ou Hôtel)")),
                ('adresseHote', models.CharField(max_length=100, verbose_name="Adresse de l'hôte")),
                ('emailHote', models.CharField(max_length=50, verbose_name="Email de l'hôte")),
                ('contactHote', models.CharField(max_length=15, verbose_name="Téléphone de l'hôte")),
                ('finance', models.PositiveSmallIntegerField(choices=[(1, 'Par vous-même'), (2, 'Par un garant')], default=2, verbose_name='Financement du voyage')),
                ('numdemande', models.CharField(max_length=25)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='john_app.Pays')),
            ],
        ),
    ]
