# Generated by Django 2.0.6 on 2020-03-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0006_pays_visa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visa',
            options={'ordering': ('numdemande',), 'verbose_name_plural': 'Demandes de Visa'},
        ),
        migrations.AddField(
            model_name='visa',
            name='statutvisa',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nouveau'), (2, 'En cours de traitement'), (3, 'Accepté'), (4, 'Refusé')], default=1, verbose_name='Status du visa'),
        ),
    ]
