# Generated by Django 2.0.6 on 2020-03-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0007_auto_20200309_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='typeDoc',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Passeport ordinaire'), (2, 'Passeport diplomatique'), (3, 'Passeport de service'), (4, 'Passeport officiel'), (5, 'Passeport spécial'), (6, 'Autre document')], default=1, verbose_name='Type Document de voyage'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='finance',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Par vous-même'), (2, 'Par un garant')], default=1, verbose_name='Financement du voyage'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='nbreIn',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Une entrée'), (2, 'Une Sortie'), (3, 'Plusieurs entrées')], default=2, verbose_name="Nombre d'entrées"),
        ),
        migrations.AlterField(
            model_name='visa',
            name='objet',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Tourisme'), (2, 'Affaires'), (3, 'Visite à la famille ou à des amis'), (4, 'Culture'), (5, 'Sports'), (6, 'Visite officielle'), (7, 'Raisons médicales'), (8, 'Etudes'), (9, 'Transit aéroportuaire'), (10, 'Autre')], default=1, verbose_name='Objet du voyage'),
        ),
    ]
