# Generated by Django 2.0.6 on 2020-03-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0008_auto_20200309_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visa',
            name='nbreIn',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Une entrée'), (2, 'Deux entrées'), (3, 'Plusieurs entrées')], default=1, verbose_name="Nombre d'entrées"),
        ),
    ]
