# Generated by Django 2.0.6 on 2020-03-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0009_auto_20200309_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pays',
            options={'ordering': ('nomPays',), 'verbose_name_plural': 'Ambassades'},
        ),
        migrations.AlterField(
            model_name='visa',
            name='numdemande',
            field=models.CharField(max_length=25, verbose_name='Numéro demande'),
        ),
    ]
