# Generated by Django 2.0.6 on 2020-03-09 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0010_auto_20200309_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='dateEdit',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AddField(
            model_name='visa',
            name='dateEnr',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Date d'enregistrement"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pays',
            name='codePays',
            field=models.IntegerField(verbose_name="Code de l'ambassade"),
        ),
        migrations.AlterField(
            model_name='pays',
            name='nomPays',
            field=models.CharField(max_length=50, verbose_name="Nom de l'ambassade"),
        ),
    ]
