# Generated by Django 2.0.6 on 2020-03-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0012_auto_20200329_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='contact2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Téléphone 2'),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='contact3',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Téléphone 3'),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='email',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Email'),
        ),
    ]
