# Generated by Django 2.0.6 on 2020-05-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0013_auto_20200331_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='email',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Email'),
        ),
    ]
