# Generated by Django 2.0.6 on 2020-05-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0014_auto_20200501_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='fonctionContact',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name="SECTEUR D'ACTIVITE"),
        ),
    ]
