# Generated by Django 2.0.6 on 2020-11-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0016_auto_20200501_0229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=160, verbose_name='Texte du message')),
                ('dateEnr', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('source', models.PositiveSmallIntegerField(choices=[(1, 'Chez John'), (2, 'Client')], default=2)),
            ],
        ),
    ]
