# Generated by Django 2.0.6 on 2020-11-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0017_marketing'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketing',
            name='frequence',
            field=models.IntegerField(default=1, verbose_name='Fréquence'),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='texte',
            field=models.TextField(verbose_name='Texte du message'),
        ),
    ]
