# Generated by Django 2.0.6 on 2020-11-08 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0018_auto_20201108_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketing',
            name='deadline',
            field=models.IntegerField(default=0, verbose_name='Deadline'),
        ),
    ]
