# Generated by Django 2.0.6 on 2020-11-08 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0019_marketing_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketing',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='john_app.Abonnement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marketing',
            name='source',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Client'), (2, 'Chez John')], default=2),
        ),
    ]
