# Generated by Django 2.0.6 on 2020-11-08 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0020_auto_20201108_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobilier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typevilla', models.PositiveSmallIntegerField(choices=[(1, 'Terrain'), (2, 'Villa'), (3, 'Appartement'), (4, 'Immeuble')], default=2)),
                ('piece', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 x 1'), (2, '2 x 1'), (3, '3 x 1'), (4, '4 x 1'), (5, 'Autre')], default=1, null=True)),
                ('etage', models.IntegerField(blank=True, default=0, null=True)),
                ('superficie', models.IntegerField(blank=True, default=0, null=True)),
                ('cout', models.IntegerField(default=0)),
                ('vente', models.BooleanField(default=False)),
                ('commune', models.CharField(max_length=50)),
                ('dateEnr', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='john_app.Abonnement')),
            ],
        ),
    ]
