# Generated by Django 2.2.6 on 2020-11-15 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0021_mobilier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilier',
            name='commune',
        ),
    ]
