# Generated by Django 2.2.6 on 2020-11-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0022_remove_mobilier_commune'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilier',
            name='commune',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Bandalungwa'), (2, 'Barumbu'), (3, 'Bumbu'), (4, 'Gombe'), (5, 'Kalamu'), (6, 'Kasa-Vubu'), (7, 'Kimbanseke'), (8, 'Kinshasa'), (9, 'Kintambo'), (10, 'Kisenso'), (11, 'Lemba'), (12, 'Limete'), (13, 'Lingwala'), (14, 'Makala'), (15, 'Maluku'), (16, 'Masina'), (17, 'Matete'), (18, 'Mont-Ngafula'), (19, 'Ndjili'), (20, 'Ngaba'), (21, 'Ngaliema'), (22, 'Ngiri-Ngiri'), (23, 'Nsele'), (24, 'Selembao')], default=1, null=True),
        ),
    ]
