# Generated by Django 2.2.6 on 2020-11-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0023_mobilier_commune'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilier',
            name='adresseUrl',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
