# Generated by Django 2.2.6 on 2020-11-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0024_mobilier_adresseurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilier',
            name='actif',
            field=models.BooleanField(default=False),
        ),
    ]
