# Generated by Django 2.2.6 on 2020-11-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0025_mobilier_actif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilier',
            name='etage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobilier',
            name='superficie',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
