# Generated by Django 2.2.6 on 2020-11-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0026_auto_20201119_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilier',
            name='piece',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 x 1'), (2, '2 x 1'), (3, '3 x 1'), (4, '4 x 1'), (5, 'Autre')], null=True),
        ),
    ]
