# Generated by Django 2.2.6 on 2020-11-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0027_auto_20201123_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilier',
            name='piece',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 x 1'), (2, '2 x 1'), (3, '3 x 1'), (4, '4 x 1'), (5, 'Autre')], default=5, null=True),
        ),
        migrations.AlterField(
            model_name='mobilier',
            name='typevilla',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Terrain'), (2, 'Villa'), (3, 'Appartement'), (4, 'Immeuble'), (5, 'Autre')], default=2),
        ),
    ]
