# Generated by Django 2.2.6 on 2020-11-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0028_auto_20201123_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilier',
            name='garanty',
            field=models.IntegerField(default=3),
        ),
    ]
