# Generated by Django 2.2.6 on 2020-12-02 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0029_mobilier_garanty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=10)),
                ('actif', models.BooleanField(default=False)),
                ('dateEnr', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
            ],
        ),
        migrations.CreateModel(
            name='Gift_Gain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateGain', models.DateTimeField(auto_now_add=True, verbose_name='Date gain')),
                ('client', models.ForeignKey(on_delete=None, to='john_app.Abonnement')),
                ('gift', models.ForeignKey(on_delete=None, to='john_app.Gift')),
            ],
        ),
    ]
