# Generated by Django 2.2.6 on 2020-12-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0031_auto_20201202_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='dateGain',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de gain'),
        ),
        migrations.AlterField(
            model_name='gift_gain',
            name='dateGain',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de gain'),
        ),
    ]
