# Generated by Django 2.2.6 on 2020-12-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0032_auto_20201205_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift_gain',
            name='codeGift',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
