# Generated by Django 2.2.6 on 2020-12-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0033_gift_gain_codegift'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift_gain',
            name='livraison',
            field=models.BooleanField(default=False),
        ),
    ]
