# Generated by Django 2.2.6 on 2020-12-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0034_gift_gain_livraison'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personne', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=15)),
                ('lieu', models.CharField(max_length=200)),
                ('deadline_date', models.DateField()),
                ('deadline_time', models.TimeField()),
                ('dateEnr', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('dateEdit', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('code', models.CharField(max_length=10)),
                ('annuler', models.BooleanField(default=False)),
                ('effectif', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=None, to='john_app.Abonnement')),
            ],
        ),
    ]
