# Generated by Django 2.2.6 on 2020-12-08 00:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0035_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
