# Generated by Django 2.2.6 on 2020-12-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0036_auto_20201208_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='effectif',
            field=models.BooleanField(default=True),
        ),
    ]
