# Generated by Django 2.2.6 on 2020-12-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0037_auto_20201208_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='remarque',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
