# Generated by Django 2.2.6 on 2020-12-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0038_meeting_remarque'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketing',
            name='moderation',
            field=models.BooleanField(default=False),
        ),
    ]
