# Generated by Django 2.2.6 on 2020-12-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0039_marketing_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=15)),
                ('marque', models.CharField(max_length=50)),
                ('climatisation', models.BooleanField(default=True)),
                ('contact', models.CharField(max_length=15)),
                ('actif', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=None, to='john_app.Abonnement')),
            ],
        ),
    ]
