# Generated by Django 2.2.6 on 2020-12-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0042_taxi_vip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation_taxi',
            old_name='lieu',
            new_name='destination',
        ),
        migrations.AddField(
            model_name='reservation_taxi',
            name='origine',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
