# Generated by Django 2.2.6 on 2020-12-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0043_auto_20201213_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation_taxi',
            name='Taxi',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='john_app.Taxi'),
        ),
    ]
