# Generated by Django 2.2.6 on 2020-12-13 13:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0044_auto_20201213_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation_taxi',
            name='climatisation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reservation_taxi',
            name='dateEnr',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Date d'enregistrement"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation_taxi',
            name='vip',
            field=models.BooleanField(default=False),
        ),
    ]
