# Generated by Django 2.2.6 on 2020-12-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0045_auto_20201213_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation_taxi',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
    ]
