# Generated by Django 2.2.6 on 2020-12-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0046_reservation_taxi_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='client',
            field=models.ForeignKey(default=9, on_delete=None, to='john_app.Abonnement'),
            preserve_default=False,
        ),
    ]
