# Generated by Django 2.2.6 on 2020-12-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0047_visa_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=15)),
                ('client', models.ForeignKey(on_delete=None, to='john_app.Abonnement')),
            ],
        ),
    ]
