# Generated by Django 2.2.6 on 2020-12-13 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0048_carnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='carnet',
            name='dateEnr',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Date d'enregistrement"),
            preserve_default=False,
        ),
    ]
