# Generated by Django 2.2.6 on 2020-12-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0051_voyage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Dimanche'), (2, 'Lundi'), (3, 'Mardi'), (4, 'Mercredi'), (5, 'Jeudi'), (6, 'Vendredi'), (7, 'Samedi')], default=2, null=True)),
                ('heure_departure', models.TimeField()),
                ('heure_arrival', models.TimeField()),
                ('numvol', models.CharField(max_length=6)),
                ('escale', models.CharField(max_length=40)),
                ('aircraft', models.ForeignKey(on_delete=None, to='john_app.Aircraft')),
                ('voyage', models.ForeignKey(on_delete=None, to='john_app.Voyage')),
            ],
        ),
    ]
