# Generated by Django 2.2.6 on 2020-12-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0052_horaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif_Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passager', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Adulte'), (2, 'Enfant'), (3, 'Bébé')], default=1, null=True)),
                ('classe', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Primière Classe'), (2, 'Deuxième Classe'), (3, 'Autre')], default=2, null=True)),
                ('tarif', models.FloatField(default=0)),
                ('aircraft', models.ForeignKey(on_delete=None, to='john_app.Aircraft')),
                ('voyage', models.ForeignKey(on_delete=None, to='john_app.Voyage')),
            ],
        ),
    ]
