# Generated by Django 2.2.6 on 2020-12-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0053_tarif_aircraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarif_aircraft',
            name='classe',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Primière'), (2, 'Business'), (3, 'Economique'), (4, 'Autre')], default=3, null=True),
        ),
    ]
