# Generated by Django 2.2.6 on 2020-12-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0054_auto_20201218_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft_Available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Primière'), (2, 'Business'), (3, 'Economique'), (4, 'Autre')], default=3, null=True)),
                ('nombre', models.IntegerField(default=0)),
                ('aircraft', models.ForeignKey(on_delete=None, to='john_app.Aircraft')),
                ('voyage', models.ForeignKey(on_delete=None, to='john_app.Voyage')),
            ],
        ),
    ]
