# Generated by Django 2.2.6 on 2020-12-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0055_aircraft_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft_available',
            name='jour',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Dimanche'), (2, 'Lundi'), (3, 'Mardi'), (4, 'Mercredi'), (5, 'Jeudi'), (6, 'Vendredi'), (7, 'Samedi')], default=2, null=True),
        ),
        migrations.AddField(
            model_name='aircraft_available',
            name='numvol',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
    ]
