# Generated by Django 2.2.6 on 2020-12-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0056_auto_20201218_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft_Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numvol', models.CharField(max_length=6)),
                ('jour', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Dimanche'), (2, 'Lundi'), (3, 'Mardi'), (4, 'Mercredi'), (5, 'Jeudi'), (6, 'Vendredi'), (7, 'Samedi')], default=2, null=True)),
                ('classe', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Primière'), (2, 'Business'), (3, 'Economique'), (4, 'Autre')], default=3, null=True)),
                ('adulte', models.IntegerField(default=1)),
                ('child', models.IntegerField(default=0)),
                ('infant', models.IntegerField(default=0)),
                ('code', models.CharField(max_length=10)),
                ('statutreservation', models.PositiveSmallIntegerField(choices=[(1, 'Nouveau'), (2, 'En cours de traitement'), (3, 'Validée'), (4, 'Annulée')], default=1)),
                ('aircraft', models.ForeignKey(on_delete=None, to='john_app.Aircraft')),
                ('client', models.ForeignKey(on_delete=None, to='john_app.Abonnement')),
            ],
        ),
    ]
