# Generated by Django 2.2.6 on 2020-12-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0060_auto_20201218_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft_reservation',
            name='statutreservation',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nouveau'), (2, 'En cours de traitement'), (3, 'Confirmée'), (4, 'Annulée')], default=1),
        ),
    ]
