# Generated by Django 2.2.6 on 2021-01-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0061_auto_20201221_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visa',
            name='adresseHote',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Adresse de l'hôte"),
        ),
        migrations.AlterField(
            model_name='visa',
            name='contactHote',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name="Téléphone de l'hôte"),
        ),
        migrations.AlterField(
            model_name='visa',
            name='emailHote',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Email de l'hôte"),
        ),
        migrations.AlterField(
            model_name='visa',
            name='finance',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Par vous-même'), (2, 'Par un garant')], default=1, null=True, verbose_name='Financement du voyage'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='hote',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Nom de l'hôte (Personne ou Hôtel)"),
        ),
        migrations.AlterField(
            model_name='visa',
            name='statutvisa',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Nouveau'), (2, 'En cours de traitement'), (3, 'Accepté'), (4, 'Refusé')], default=1, null=True, verbose_name='Status du visa'),
        ),
    ]
