# Generated by Django 2.2.6 on 2021-01-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0062_auto_20210128_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visa',
            name='info',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Informations complémentaires'),
        ),
    ]
