# Generated by Django 2.2.6 on 2021-01-31 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0063_auto_20210128_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation_taxi',
            name='cout',
            field=models.IntegerField(default=10),
        ),
    ]
