# Generated by Django 2.2.6 on 2021-02-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0064_reservation_taxi_cout'),
    ]

    operations = [
        migrations.AddField(
            model_name='pays',
            name='facilities',
            field=models.BooleanField(default=False),
        ),
    ]
