# Generated by Django 2.2.6 on 2021-02-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0065_pays_facilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filiales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiale', models.CharField(max_length=50)),
                ('pays', models.ForeignKey(on_delete=None, to='john_app.Pays')),
            ],
        ),
    ]
