# Generated by Django 2.2.6 on 2021-02-02 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0066_filiales'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Filiales',
            new_name='Filiale',
        ),
    ]
