# Generated by Django 2.2.6 on 2021-02-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0068_filiale_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visa',
            name='pays',
            field=models.ForeignKey(on_delete=None, to='john_app.Pays'),
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Affaires'), (2, 'Etude'), (3, 'Santé'), (4, 'Tourisme')], default=2, null=True)),
                ('client', models.ForeignKey(on_delete=None, to='john_app.Abonnement')),
                ('filiale', models.ForeignKey(blank=True, null=True, on_delete=None, to='john_app.Filiale')),
                ('pays', models.ForeignKey(on_delete=None, related_name='Country', to='john_app.Pays')),
            ],
        ),
    ]
