# Generated by Django 2.2.6 on 2021-02-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0070_facilities_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilities',
            name='motif',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Affaires'), (2, 'Etudes'), (3, 'Santé'), (4, 'Tourisme')], default=2, null=True),
        ),
    ]
