# Generated by Django 2.2.6 on 2021-02-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0071_auto_20210202_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilities',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
