# Generated by Django 2.2.6 on 2021-02-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0072_auto_20210202_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation_Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbrCouvert', models.IntegerField()),
                ('personne', models.CharField(max_length=50)),
                ('date_reservation', models.DateField()),
                ('heure_reservation', models.TimeField()),
                ('client', models.ForeignKey(on_delete=None, related_name='Client', to='john_app.Abonnement')),
                ('restaurant', models.ForeignKey(on_delete=None, related_name='Restaurant', to='john_app.Abonnement')),
            ],
        ),
    ]
