# Generated by Django 2.2.6 on 2021-02-05 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0073_reservation_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketing',
            name='deadline',
        ),
    ]
