# Generated by Django 2.2.6 on 2021-02-05 23:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0074_remove_marketing_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketing',
            name='date_deadline',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Deadline'),
            preserve_default=False,
        ),
    ]
