# Generated by Django 2.2.6 on 2021-02-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0075_marketing_date_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketing_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=15)),
                ('client', models.ForeignKey(on_delete=None, to='john_app.Abonnement')),
            ],
        ),
    ]
