# Generated by Django 2.2.6 on 2021-02-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0077_auto_20210209_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cout_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.PositiveSmallIntegerField(choices=[(1, 'Abonnement'), (2, 'Visa'), (3, 'Voyage'), (4, 'Marketing'), (5, 'Taxi'), (6, 'Mobilier')], default=1)),
                ('cout', models.FloatField(default=0.2)),
                ('pourcentageDFS', models.FloatField(default=0.7)),
                ('pourcentagePartenaire', models.FloatField(default=0.3)),
                ('periodicity', models.PositiveSmallIntegerField(choices=[(1, 'Cash'), (2, 'Jour'), (3, 'Mois')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Taux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de', models.DateTimeField()),
                ('a', models.DateTimeField()),
                ('taux', models.FloatField()),
            ],
        ),
    ]
