# Generated by Django 2.2.6 on 2021-02-10 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0078_cout_service_taux'),
    ]

    operations = [
        migrations.AddField(
            model_name='cout_service',
            name='dateEdit',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AddField(
            model_name='cout_service',
            name='dateEnr',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Date d'enregistrement"),
            preserve_default=False,
        ),
    ]
