# Generated by Django 2.2.6 on 2021-02-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0079_auto_20210210_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.PositiveSmallIntegerField(choices=[(1, 'Abonnement'), (2, 'Visa'), (3, 'Voyage'), (4, 'Marketing'), (5, 'Taxi'), (6, 'Mobilier')], default=1)),
                ('gainDFS_USD', models.FloatField()),
                ('gainDFS_CDF', models.FloatField()),
                ('partenaire', models.CharField(max_length=50)),
                ('gainPartenaire_USD', models.FloatField()),
                ('gainPartenaire_CDF', models.FloatField()),
                ('reference', models.CharField(blank=True, max_length=15, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('dateEnr', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('client', models.ForeignKey(on_delete=None, to='john_app.Abonnement')),
            ],
        ),
    ]
