# Generated by Django 2.2.6 on 2021-02-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0080_cash_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
