# Generated by Django 2.2.6 on 2021-02-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0081_abonnement_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash_book',
            name='service',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Abonnement'), (2, 'Visa'), (3, 'Voyage'), (4, 'Marketing'), (5, 'Taxi Simple'), (6, 'Taxi Clim'), (7, 'Taxi VIP'), (8, 'Mobilier')], default=1),
        ),
        migrations.AlterField(
            model_name='cout_service',
            name='service',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Abonnement'), (2, 'Visa'), (3, 'Voyage'), (4, 'Marketing'), (5, 'Taxi Simple'), (6, 'Taxi Clim'), (7, 'Taxi VIP'), (8, 'Mobilier')], default=1),
        ),
        migrations.AlterField(
            model_name='taux',
            name='a',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
