# Generated by Django 2.2.6 on 2021-02-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0082_auto_20210211_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash_book',
            name='cashNumber',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cash_book',
            name='transactionNumber',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cash_book',
            name='partenaire',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
