# Generated by Django 2.2.6 on 2021-02-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0083_auto_20210211_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash_book',
            name='transactionNumber',
        ),
        migrations.AddField(
            model_name='taux',
            name='actif',
            field=models.BooleanField(default=False),
        ),
    ]
