# Generated by Django 2.2.6 on 2021-02-11 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0084_auto_20210211_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash_book',
            name='partenaire',
        ),
    ]
