# Generated by Django 2.2.6 on 2021-02-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0085_remove_cash_book_partenaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash_book',
            name='partenaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, related_name='Partenaire', to='john_app.Abonnement'),
        ),
    ]
