# Generated by Django 2.2.6 on 2021-02-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0086_cash_book_partenaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation_restaurant',
            name='code_reservation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cash_book',
            name='service',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Abonnement'), (2, 'Visa'), (3, 'Voyage'), (4, 'Marketing'), (5, 'Taxi Simple'), (6, 'Taxi Clim'), (7, 'Taxi VIP'), (8, 'Mobilier'), (9, 'Restaurant')], default=1),
        ),
        migrations.AlterField(
            model_name='cout_service',
            name='service',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Abonnement'), (2, 'Visa'), (3, 'Voyage'), (4, 'Marketing'), (5, 'Taxi Simple'), (6, 'Taxi Clim'), (7, 'Taxi VIP'), (8, 'Mobilier'), (9, 'Restaurant')], default=1),
        ),
    ]
