# Generated by Django 2.2.6 on 2021-02-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0087_auto_20210212_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilities',
            name='numdemande',
            field=models.CharField(default='', max_length=15, verbose_name='Numéro demande'),
            preserve_default=False,
        ),
    ]
