# Generated by Django 2.2.6 on 2021-02-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0088_facilities_numdemande'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilities',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
    ]
