# Generated by Django 2.2.6 on 2021-02-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john_app', '0089_facilities_cancel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilities',
            name='cancel',
        ),
        migrations.AddField(
            model_name='reservation_restaurant',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
    ]
